from decompress import decompress
from compress import compress
import time
import os

# for i in range(1,4):
#     t=time.time()
#     compress(f"./data/file{i}.txt")
#     comp_time = (time.time()-t)
#     size1,size2=os.path.getsize(f"./data/file{i}.txt"),os.path.getsize(f"./data/file{i}.lzw")
#     t=time.time()
#     decompress(f"./data/file{i}.lzw", f"./data/file{i}_d.txt")
#     decomp_time = (time.time()-t)
#     size3=os.path.getsize(f"./data/file{i}_d.txt")
#     print("Size before compression:", size1/1024, "KB")
#     print("Size after compression:", size2/1024, "KB")
#     print("Size after decompression:",size3/1024,"KB")
#     print("Compression ratio:",size2/size1)
#     print(f"Compress time: {comp_time}s")
#     print(f"Decompress time: {decomp_time}s")
#     print("="*50)

t=time.time()
compress(f"./data/img1.jpg")
comp_time = (time.time()-t)
size1,size2=os.path.getsize(f"./data/img1.jpg"),os.path.getsize(f"./data/img1.lzw")
t=time.time()
decompress(f"./data/img1.lzw", f"./data/img1_d.jpg")
decomp_time = (time.time()-t)
size3=os.path.getsize(f"./data/img1_d.jpg")
print("Size before compression:", size1/1024, "KB")
print("Size after compression:", size2/1024, "KB")
print("Size after decompression:",size3/1024,"KB")
print("Compression ratio:",size2/size1)
print(f"Compress time: {comp_time}s")
print(f"Decompress time: {decomp_time}s")
print("="*50)

t=time.time()
compress(f"./data/img2.png")
comp_time = (time.time()-t)
size1,size2=os.path.getsize(f"./data/img2.png"),os.path.getsize(f"./data/img2.lzw")
t=time.time()
decompress(f"./data/img2.lzw", f"./data/img2_d.png")
decomp_time = (time.time()-t)
size3=os.path.getsize(f"./data/img2_d.png")
print("Size before compression:", size1/1024, "KB")
print("Size after compression:", size2/1024, "KB")
print("Size after decompression:",size3/1024,"KB")
print("Compression ratio:",size2/size1)
print(f"Compress time: {comp_time}s")
print(f"Decompress time: {decomp_time}s")
print("="*50)

t=time.time()
compress(f"./data/img3.tiff")
comp_time = (time.time()-t)
size1,size2=os.path.getsize(f"./data/img3.tiff"),os.path.getsize(f"./data/img3.lzw")
t=time.time()
decompress(f"./data/img3.lzw", f"./data/img3_d.tiff")
decomp_time = (time.time()-t)
size3=os.path.getsize(f"./data/img3_d.tiff")
print("Size before compression:", size1/1024, "KB")
print("Size after compression:", size2/1024, "KB")
print("Size after decompression:",size3/1024,"KB")
print("Compression ratio:",size2/size1)
print(f"Compress time: {comp_time}s")
print(f"Decompress time: {decomp_time}s")
print("="*50)